# Generated by Django 5.0.1 on 2024-01-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_comment_parent_comment_delete_threadtweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoutetweet',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotetweet_post', to='Post.post'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repost_post', to='Post.post'),
        ),
    ]
