# Generated by Django 5.0.1 on 2024-01-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_alter_qoutetweet_post_alter_repost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
